# Generated by Django 4.1.7 on 2023-03-14 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RidingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'riding_style',
                'verbose_name_plural': 'riding_stylies',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='products_images')),
                ('riding_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.ridingstyle')),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
            },
        ),
    ]
