version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      .env
  project:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sw_docker
    depends_on:
      - db
    volumes:
      - .:/backend
      - ./static:/backend/static
    env_file:
      - .env
    entrypoint: bash ./run_backends.sh
    ports:
      - '8000:8000'
