# Generated by Django 4.1.7 on 2023-03-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_instructor',
        ),
    ]
