# Generated by Django 4.1.7 on 2023-03-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
